name: Scorecard Evaluation Workflow
on:
  workflow_dispatch:
    inputs:
      testset_id:
        description: Testset ID
        required: true
      scoring_config_id:
        description: Scoring Config ID
        required: true
  repository_dispatch:
    types: start-evaluation
  pull_request:
    branches:
      - master
    types:
      - opened
permissions:
  contents: read
jobs:
  evaluation-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run test
        env:
          SCORECARD_API_KEY: ${{ secrets.SCORECARD_API_KEY }}
          TESTSET_ID: ${{ github.event.inputs.testset_id ||
            github.event.client_payload.testset_id  }}
          SCORING_CONFIG_ID: ${{ github.event.inputs.scoring_config_id ||
            github.event.client_payload.scoring_config_id }}
        run: python3 run_tests.py
    if: github.event.name == 'pull_request'
